database:
  dbdriver: postgres
  dbsource: postgresql://root:root@localhost:5432/simple_bank?sslmode=disable
security:
  TOKEN_SYMMETRIC_KEY: 12345678901234567890123456789012
  ACCESS_TOKEN_DURATION: 15m
  REFRESH_TOKEN_DURATION: 24h

server:
  address: 0.0.0.0:8080